# Generated by Django 3.1.2 on 2020-11-15 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('two_app', '0002_auto_20201115_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register1',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
