# Generated by Django 3.1.2 on 2020-11-18 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('two_app', '0003_auto_20201115_1903'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bookings2',
        ),
        migrations.AddField(
            model_name='register1',
            name='name',
            field=models.CharField(default=True, max_length=334),
            preserve_default=False,
        ),
    ]
