# Generated by Django 3.1.2 on 2020-11-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('two_app', '0004_auto_20201118_1859'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookings2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=334)),
                ('name', models.CharField(max_length=334)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_no', models.CharField(max_length=334)),
                ('adhaarcard', models.CharField(max_length=334)),
                ('category', models.CharField(max_length=334)),
                ('issue', models.CharField(max_length=334)),
                ('your_status', models.IntegerField()),
                ('present_status', models.IntegerField()),
                ('treatment', models.BooleanField(default=False)),
            ],
        ),
    ]
