# Generated by Django 3.1.2 on 2020-11-22 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('two_app', '0005_bookings2'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctor_register1',
            fields=[
                ('username', models.CharField(max_length=334)),
                ('name', models.CharField(max_length=334)),
                ('email', models.CharField(max_length=334)),
                ('mobile_no', models.CharField(max_length=334)),
                ('password', models.CharField(max_length=334)),
                ('adhaarcard', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('type_doctor', models.CharField(max_length=334)),
                ('address', models.TextField()),
            ],
        ),
    ]
